import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import "./assets/css/response.css";
import BootstrapClient from './components/BootstrapClient';
import Header from './components/Header';
import Footer from './components/Footer';

export const metadata = {
  title: "Weforce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* Update the favicon link */}
        <link rel="shortcut icon" href="/favicon.ico" />
        <link href="https://fonts.cdnfonts.com/css/helvetica-neue-5" rel="stylesheet" />
      </head>

      <body>
        <Header />
        {children}
        <BootstrapClient />
        <Footer />
      </body>
    </html>
  );
}
